### ISSUE TITLE
Error: Cannot find module './lib/loggers'

### ISSUE THREAD

**Issue by Offirmo** [maxlath/wikidata-token#1]
Seems you have an hidden dependency

``` js
const wdToken = require('wikidata-token');

const config = {username: 'Xyz', password: '****'};
const getToken = wdToken(config);

getToken()
.then(data => console.log('token :', data));
```

```
Error: Cannot find module './lib/loggers'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (xxx/node_modules/wikidata-token/node_modules/inv-loggers/inv-loggers.coffee:1:80)
```

**Comment by Offirmo** [comment]
Correction : seems it tries to load a raw coffee file. Is a logger really needed in such a small module ?

**Comment by maxlath** [comment]
I cleaned up a bit, removing the dependency to inv-loggers 3cb16cf
How is that working now?
